# Easily switch primary foreground/background colors
DEFAULT_BACKGROUND=235
DEFAULT_FOREGROUND=006
ALT_BACKGROUND=006
ALT_FOREGROUND=235
DEFAULT_COLOR=${DEFAULT_FOREGROUND}

typeset -g POWERLEVEL9K_MODE="nerdfont-complete"

typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=" " 
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR="\uE0C8"
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=""
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  time
  load
  go_version
  python_version
  kube_context
  vcs
  newline
  status
  command_execution_time
  context
  dir_writable
  dir
  root_indicator
)



typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE="\uF109 %m"
typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="${DEFAULT_FOREGROUND}"
typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="${DEFAULT_BACKGROUND}"
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="${DEFAULT_FOREGROUND}"
typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="${DEFAULT_BACKGROUND}"
typeset -g POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=false

typeset -g POWERLEVEL9K_VCS_{CLEAN,MODIFIED,UNTRACKED}_FOREGROUND="${DEFAULT_BACKGROUND}"
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND="green"
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="yellow"
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="magenta"

typeset -g POWERLEVEL9K_DIR_SHORTEN_DIR_LENGTH=5
typeset -g POWERLEVEL9K_DIR_SHORTEN_STRATEGY="truncate_to_unique"
POWERLEVEL9K_DIR_HOME_BACKGROUND="${DEFAULT_FOREGROUND}"
POWERLEVEL9K_DIR_HOME_FOREGROUND="${DEFAULT_BACKGROUND}"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="${DEFAULT_FOREGROUND}"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="${DEFAULT_BACKGROUND}"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="${DEFAULT_FOREGROUND}"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUN="${DEFAULT_BACKGROUND}"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="${DEFAULT_FOREGROUND}"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="${DEFAULT_BACKGROUND}"

POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_STATUS_CROSS=false
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_OK_BACKGROUND="${DEFAULT_BACKGROUND}"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="${DEFAULT_BACKGROUND}"
#
POWERLEVEL9K_TIME_FORMAT="%D{%T }" # 15:29:33
#POWERLEVEL9K_TIME_FORMAT="\uF017 %D{%T }" #  15:29:33
POWERLEVEL9K_TIME_FOREGROUND="${DEFAULT_FOREGROUND}"
POWERLEVEL9K_TIME_BACKGROUND="${DEFAULT_BACKGROUND}"
typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=''

#POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
#POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3
#POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="${DEFAULT_FOREGROUND}"
#POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="${DEFAULT_BACKGROUND}"
#POWERLEVEL9K_COMMAND_EXECUTION_TIME_ICON="\u23F1"

#POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="${DEFAULT_FOREGROUND}"
#POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="magenta"
#POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="${DEFAULT_BACKGROUND}"
#POWERLEVEL9K_USER_ROOT_ICON=$'\uF198'  # 

#POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="${DEFAULT_BACKGROUND}"
#POWERLEVEL9K_LOAD_WARNING_BACKGROUND="${DEFAULT_BACKGROUND}"
#POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="${DEFAULT_BACKGROUND}"
#POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="red"
#POWERLEVEL9K_LOAD_WARNING_FOREGROUND="yellow"
#POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="green"
#POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
#POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
#POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"
typeset -g POWERLEVEL9K_LOAD_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_LOAD_WHICH=1
#
typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND="${DEFAULT_BACKGROUND}"
typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND="${DEFAULT_FOREGROUND}"

typeset -g POWERLEVEL9K_PYTHON_VERSION_BACKGROUND="${ALT_BACKGROUND}"
typeset -g POWERLEVEL9K_PYTHON_VERSION_FOREGROUND="${ALT_FOREGROUND}"

typeset -g POWERLEVEL9K_KUBE_CONTEXT_BACKGROUND="${DEFAULT_BACKGROUND}"
typeset -g POWERLEVEL9K_KUBE_CONTEXT_FOREGROUND="${DEFAULT_FOREGROUND}"

